### PR TITLE
Added formatter and parser functions to allow moment.js alternatives

### LINKED ISSUE #277: Feature request: parse and format hooks
Pikaday + Moment.js is great, but moment.js adds an additional 12.5kB gzipped to the page load which is wasted bytes if the only place in the browser you're using date parsing/formatting is specifically for dealing with datepickers.

In these cases a lightweight, less-flexible date parsing and formatting function would work just as well for a fraction of the bytes. In my current application, I'm manually formatting and setting the parsed value in Pikaday's `onSelect` callback, however this callback fires _after_ the original unformatted value is set back to the field. This has a number of drawbacks, the main one being that I am hooked into the onchange event on said field, which then fires with an invalid, unformatted value.

I would love to see an onFormat callback that works a little like this:

```
new Pikaday({
  field: document.selectElementById('myField'),
  format: function (date) {
     var formattedValue;
     // Do some formatting here...
     return formattedValue;
  }, 
  parse: function (dateString) {
    // Do some custom parsing
    return parsedDate;
  }
});
```

You could then, if you chose, use moment.js like any other formatter, by passing the moment constructor to parse and moment.format to format.

### PR DESCRIPTION
**Pull request by HowlingEverett**
Fixes #277. I haven't removed any of the moment.js checking and direct use, but this mechanism could remove even the soft dependency on moment.js, since it's easy to push the moment() and moment.format() functions in as parser and formatter respectively.

### CODE REVIEW

**Comment by jashmenn** [comment]
Another reason this is great is because sometimes you want to parse and display different formats. Moment is really generous in how it will parse if you have no format, but in `master` if you have no format the display looks really ugly (even though parsing will work great).

**Comment by jashmenn** [comment]
One problem with this pull is that the logic to use `opts.parser` doesn't allow for custom parsing with moment. 

E.g. https://github.com/dbushell/Pikaday/pull/278/files#diff-5e6a2e8d597bd0e8a3111ba17c4a0815R468 starts with 

`if (hasMoment)`

Ideally if someone passes `opts.parser` we should use it whether or not moment is installed.

**Comment by alexcroox** [comment]
+1 I just want `d/m/y' but I have to include 102 KB to achieve that :(

**Comment by wojciechczerniak** [comment]
`toString` and `parse` options were added in v1.6.0. Thanks for your work!

**Pull request closed without merging**
