### PR TITLE
change week numbers to comply with ISO 8601

### PR DESCRIPTION
**Pull request by ctcpip**

### CODE REVIEW

**Comment by hendelth** [comment]
if moment.js is available and set to the required language, then
weekNum = moment(new Date(y, m, d)).week();
will yield the correct result.

**Comment by thijsvdanker** [comment]
@hendelth shouldn't that be 
`weekNum = moment(new Date(y, m, d)).isoWeek();`
http://momentjs.com/docs/#/get-set/iso-week/

Looks like this commit https://github.com/actano/Pikaday/commit/fd4cdc30d85faf0029f3d935465866851f887e33 in #388 supports both the moment way and the vanilla JS approach.

**Comment by jazen** [comment]
I fixed it in our fork and [also created a PR for Pikaday](https://github.com/dbushell/Pikaday/pull/473).

**Comment by wojciechczerniak** [comment]
Duplicate of #473

**Pull request closed without merging**
