### PR TITLE
Added space between attribute selected and disabled to avoid when the…

### PR DESCRIPTION
**Pull request by TommySorensen**
When minDate and maxDate is enabled the user is able to first pick a date like 2016-10-01 and then use the year dropdown to select a date in  2017. This causes for the selected option month both (i === month ? ' selected': '') and (isMinYear && i < opts.minMonth) || (isMaxYear && i > opts.maxMonth) to be true. I therefore added a space to avoid the two attributes to collide.

image

### CODE REVIEW

**Comment by TommySorensen** [comment]
@dbushell Can you please merge this pull request into the solution? :) Thank you

**Comment by bersujamu** [comment]
Hi @TommySorensen , let me mention @rikkert

**Comment by rikkert** [comment]
Thanks if you don't mind updating to latest I will happily merge it

**Comment by TommySorensen** [comment]
@rikkert I have merged latest changes now

**Comment by wojciechczerniak** [comment]
Merged in #526. Thanks for PR!

**Pull request closed without merging**
